* Test Case: Switchgrass prior and posterior runs
**  Running from the desktop
    1) install pecan_1.1 virtual machine
       - download pecan_1.1.ova
       - import into virtualbox
	 - open virtualbox -> file -> import appliance -> choose -> pecan_1.1.ova
    2) Launch pecan_1.1 virtual machine
       - open virtualbox -> select pecan_1.1 -> start -> login (pecan) and password (pecan11)
    3) To execute workflow click on the following desktop icons, in order:
       1) "Query BETY"
       2) "Meta-analysis"
       3) "Write Configs"
       4) "Start Runs"
       5) "Read Output"
       6) "Sensitivity Analysis"
       7) "Variance Decomposition"
#+begin_src bash
cd pecan

#+end_src

* Module Definitions
In all cases pecan/bash/scriptname.sh calls pecan/rscripts/scriptname.R. These script pairs represent workflow modules.
** Query BETY 
*** name: query.bety.R
*** Description: extracts prior distributions for specified pfts, and trait data for any species associated with pft 
*** Inputs:
**** settings file: xml file containing inputs
***** settings$database: database connection information
***** pft$name: name of pft used to link to BETY database pfts table, and to query species from BETY 
***** pft$constants: fixed parameter values 
**** trait.names: a list of plant trait parameters currently hard-coded into the script
**** from BETY:
***** spstr: string of comma delimited, specie_id values in quotes. Used to query trait data associated with these species. These are the species linked to pft$name by the pfts_species table
***** prior.distns: table of prior distributions. These are used in the meta-analysis. These are queried from the priors table, and are selected by linking the settings pft$name to pfts.name in the database, which is linked to the priors table by the pfts_priors lookup table.

*** Outputs
**** trait.data.Rdata: Used in Meta Analysis contains list 'trait.data', containing one table per trait.  Tables have columns Y, n, site, trt, ghs, obs.prec, se, and cite. These columns are derived from bety using the query.bety.trait.data function with the following relationships: Y = traits.mean, n = traits.n, site = traits.site_id, trt = traits.treatment_id, ghs = treatments.greenhouse, obs.prec = f(se), se = f(traits.stat, traits.statname), and cite = citation_id. the site, trt, and ghs values in the database have been converted to sequential integers starting at 1. Each row is a separate observation
**** prior.distns.Rdata: Used in Meta Analysis tables of prior distributions for each pft, one row per trait, with columns distn, parama, paramb, and n. distn is the name of one of the probability distributions supported by R (commonly gamma, beta, lognorm, weibull, norm), parama and paramb are the first and second parameters of the distribution. 
** Meta Analysis
*** name: meta.analysis.R
*** Description: calculates the posterior distribution of for traits for each pft, where there exist species-level data for the given pft x trait combination. 
*** Inputs:
**** settings file
***** meta.analysis$iter: number of steps in MCMC chain
***** pft$outdir: directory for pft-specific output
***** pft$name: name of pft
**** trait.data.Rdata: Generated by Query BETY module. Data tables for each trait by species combination
**** prior.distns.Rdata: Generated by Query BETY module. Tables of prior distributions for each pft
*** Outputs:
**** <traitname>.model.bug meta-analysis model specification in JAGS (used internally) 
**** trait.mcmc.Rdata: To be used by Write Configs. List of raw mcmc output (of class mcmc.list) with one mcmc.list per trait  
**** post.distns.Rdata: To be used in data assimilation (not currently implemented). Posterior distributions for each pft/trait combination summarized using standard distributions
**** meta.analysis.log:  for human assessment: data, meta-analysis results, MCMC diagnostics (also written to terminal)
**** ma.summaryplots.<site>.<pft><trait>.pdf: for human assessment: diagnostic plots, to check that convergence meets assumptions of MCMC method
**** posteriors.pdf: for human assessment of meta-analysis and data: plots for comparing posterior with data and prior
** Write Configs
*** name: write.configs.R
*** Description: writes configuration files used in the model runs. Model specific unit and naming conversions are made using functions found in R/model.specific.R
*** Inputs:
**** settings file
***** pft$name
***** pft$outdir
**** ED2IN template (see edin/templateED2IN*)
*** Outputs:
**** ED2INc.<pft><runid> ED2IN file for each run
**** c.<pft><runid>  configuration file for each run
*** Side Effects:
**** Deletes existing config files prior to writing new ones
** Start Runs
*** name: start.runs.R
*** Description: Starts model runs by executing bash/batch.jobs.sh
*** Inputs:
**** batch.jobs.sh: script that starts a run for each ED2IN* file generated in write.configs  
**** settings file
***** host$name: machine with model
***** host$rundir: directory where model executable is located
***** settings$pecanDir pecan home directory where bash/batch.jobs.sh resides
*** Outputs:
**** ED Model output for each <runid>
** Read Model output
*** name: get.model.output.R
*** Description
*** Inputs:
**** settings file
***** settings$run$host name of model host machine
***** settings$outdir directory in which output should be saved
**** read.output.R script with functions and code to extract model output (self contained, so it can be executed independently on model host machine)
*** Output
**** output.Rdata, to be used, e.g., in Sensitivity Analysis and Visualization modules containing (if produced):
***** ensemble.output: results from ensemble runs
***** sa.output: aboveground biomass results from sensitivity runs
** Sensitivity Analysis
*** in the context of modularization, this script is still under development
** Variance Decomposition
*** to be branched from Sensitivity Analysis module
** Visualization
*** under development, will be partially branched from current Sensitivity Analysis module
* System Requirements
** Linux
   PEcAn runs natively in a Linux operating system. 
** Macintosh, Windows, Linux, Solaris
   The PEcAn Virtual Machine can be run within Microsoft Windows,  Mac OSX, and Linux using freely available [[https://www.virtualbox.org/][VirtualBox]] software. A pre-configured machine with all dependencies is available for download through the PEcAn project website [[www.pecanproject.org]].

* Advanced Set Up (starting from pecan.ova VM)
** Create a ssh key pair
#+begin_src sh
   wget -O ~/sshkey.sh http://isda.ncsa.uiuc.edu/~kooper/EBI/sshkey.sh
   chmod 755 ~/sshkey.sh 
   ./sshkey.sh
#+end_src 
** Dependencies
*** Install dependencies
#+begin_src sh
cd pecan
sudo bash/install.dependencies.sh
#+end_src

* pecan 1.1 VM
** emacs23, org-mode, and ESS
#+begin_src sh
sudo apt-get install emacs23 ess leafpad --no-install-recommends
#+end_src
** install texlive 2011
#+begin_src sh
wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -xvf install-tl-unx.tar.gz
cd install-tl*
sudo ./install-tl
#+end_src
  1) at prompt, enter "i" to install
  2) after installation, add the following line to .bashrc
     PATH=/usr/local/texlive/2011/bin/x86_64-linux:$PATH
  3) thats it!

** windows manager: xorg and xfce4
#+begin_src sh
sudo apt-get install xfce4 xorg
#+end_src
** install guest additions
#+begin_src sh
sudo apt-get install virtualbox-ose-guest-utils virtualbox-ose-guest-x11 virtualbox-ose-guest-dkms
#+end_src
** browser
#+begin_src sh
sudo apt-get install midori
#+end_src
