
#line 3 "scanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer zz_create_buffer
#define yy_delete_buffer zz_delete_buffer
#define yy_flex_debug zz_flex_debug
#define yy_init_buffer zz_init_buffer
#define yy_flush_buffer zz_flush_buffer
#define yy_load_buffer_state zz_load_buffer_state
#define yy_switch_to_buffer zz_switch_to_buffer
#define yyin zzin
#define yyleng zzleng
#define yylex zzlex
#define yylineno zzlineno
#define yyout zzout
#define yyrestart zzrestart
#define yytext zztext
#define yywrap zzwrap
#define yyalloc zzalloc
#define yyrealloc zzrealloc
#define yyfree zzfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE zzrestart(zzin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int zzleng;

extern FILE *zzin, *zzout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up zztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up zztext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via zzrestart()), so that the user can continue scanning by
	 * just pointing zzin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when zztext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int zzleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow zzwrap()'s to do buffer switches
 * instead of setting up a fresh zzin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void zzrestart (FILE *input_file  );
void zz_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE zz_create_buffer (FILE *file,int size  );
void zz_delete_buffer (YY_BUFFER_STATE b  );
void zz_flush_buffer (YY_BUFFER_STATE b  );
void zzpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void zzpop_buffer_state (void );

static void zzensure_buffer_stack (void );
static void zz_load_buffer_state (void );
static void zz_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER zz_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE zz_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE zz_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE zz_scan_bytes (yyconst char *bytes,int len  );

void *zzalloc (yy_size_t  );
void *zzrealloc (void *,yy_size_t  );
void zzfree (void *  );

#define yy_new_buffer zz_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        zzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            zz_create_buffer(zzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        zzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            zz_create_buffer(zzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *zzin = (FILE *) 0, *zzout = (FILE *) 0;

typedef int yy_state_type;

extern int zzlineno;

int zzlineno = 1;

extern char *zztext;
#define yytext_ptr zztext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up zztext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	zzleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[253] =
    {   0,
        0,    0,    0,    0,   47,   47,    0,    0,   76,   75,
       50,   53,   75,   75,   75,   38,   39,   42,   35,   75,
       72,   75,   64,   43,   44,   75,   40,   72,   36,   37,
       45,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   52,   75,   72,   62,
       72,   72,   72,   72,   72,   47,   48,   55,   56,   50,
        0,   73,    0,   51,    0,   74,    0,   64,   72,   72,
       61,   46,   59,    0,   41,   72,   13,   31,   72,   72,
       72,   72,   72,   72,   72,    3,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,    4,

       72,   72,   72,   52,   62,   72,   63,   66,   72,   72,
        0,   70,   72,   72,   47,   48,   48,   49,   55,   61,
       72,   59,    0,    0,   72,   72,   72,   72,   72,   72,
       30,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       32,   22,   33,   72,   17,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,    0,    0,   72,    0,
       57,   72,   72,   72,   25,   72,    2,   29,   72,   72,
       34,   27,   72,   72,   72,   72,   72,   26,   72,   19,
       16,   72,   72,   65,   67,   72,   72,   72,   60,   60,
       58,   12,   10,   18,   72,   72,   72,    5,    1,   72,

       72,   72,   72,   72,   72,   72,   72,    0,   69,   72,
       72,   72,   72,   72,   72,   72,   72,   54,   28,   11,
       72,   72,    7,   72,   23,   72,   14,    8,   72,   20,
       72,   72,   72,   72,   15,   72,   21,   72,   72,   24,
       72,   72,   72,   72,    9,    6,   72,    0,   68,    0,
       71,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,    1,    1,    1,   21,   22,   22,   23,   24,   22,
       22,   22,   22,   22,   22,   25,   22,   26,   22,   22,
       22,   22,   22,   22,   27,   22,   22,   22,   22,   22,
       28,   29,   30,    1,   29,   31,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   22,   22,   41,   42,   43,
       44,   45,   22,   46,   47,   48,   49,   22,   50,   51,
       52,   53,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    4,    4,    4,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    1,    4,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    5,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[263] =
    {   0,
        0,    0,   51,   96,  244,  239,  238,  237,  230, 1123,
       53, 1123,  218,  213,  207, 1123, 1123, 1123, 1123,   42,
       46,  196,   52, 1123, 1123,  184, 1123,   57, 1123, 1123,
     1123,   65,   74,  131,   89,   98,  104,  119,  115,  130,
      142,  150,  149,  169,  168,  183,  184,   55,  216,  219,
      221,  212,   89,  222,   90,    0,   64,    0, 1123,   80,
      175, 1123,  176, 1123,  171, 1123,  152,  137,    0,  163,
      222, 1123,  236,   82, 1123,  232,  233,  235,  238,  241,
      253,  264,  267,  266,  273,  288,  290,  291,  306,  313,
      320,  321,  332,  339,  346,  343,  357,  360,  362,  365,

      379,  381,  391,  164,  420,  398, 1123,  408,  416,  426,
       99, 1123,  427,  427,    0,  130,  142, 1123,    0,  448,
       95,  453,  112,  147,  446,  456,  449,  451,  470,  473,
      475,  478,  480,  481,  488,  500,  502,  511,  510,  513,
      516,  521,  524,  534,  535,  542,  545,  553,  556,  568,
      563,  574,  566,  581,  587,  588,  128,  115,  108,  100,
       99,  595,  598,  596,  613,  619,  620,  621,  619,  635,
      642,  649,  650,  660,  663,  665,  665,  675,  686,  688,
      689,  691,  694,  696,  697,  715,  748,  721,   80,   47,
       44,  729,  730,  738,  744,  758,  739,  762,  769,  768,

      781,  779,  787,  794,  793,  797,  808,  156, 1123,  811,
      816,  818,  830,  837,  838,  848,  855,  854,  856,  857,
      862,  863,  881,  884,  886,  887,  894,  892,  911,  913,
      916,  921,  930,  938,  940,  947,  948,  949,  962,  970,
      971,  973,  980, 1009,  995,  998, 1027,  194, 1123,  217,
     1123, 1123, 1079, 1084, 1089, 1094, 1099, 1101, 1106, 1111,
     1115, 1117
    } ;

static yyconst flex_int16_t yy_def[263] =
    {   0,
      252,    1,    1,    1,  253,  253,  254,  254,  252,  252,
      252,  252,  255,  256,  257,  252,  252,  252,  252,  252,
      258,  252,  252,  252,  252,  252,  252,  258,  252,  252,
      252,  258,  258,  258,  258,  258,  258,  258,   34,   34,
       34,   34,   34,   34,   34,   34,  252,  252,  258,  252,
      258,   34,   34,   34,   44,  259,  260,  261,  252,  252,
      255,  252,  256,  252,  257,  252,  252,  252,  262,   44,
      262,  252,  252,  252,  252,   44,   44,   44,   44,   44,
       34,   44,   44,   44,   44,   44,   44,   44,   34,   34,
       34,   34,   34,   34,   34,   44,   44,   44,   44,   44,

       44,   34,   34,  252,  252,   34,  252,   34,   34,   34,
      252,  252,   34,   44,  259,  260,  260,  252,  261,  252,
      262,  252,  252,  252,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   34,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   34,
       44,   44,   44,   44,   44,   44,  252,  252,  262,  252,
      252,   44,   44,   44,   44,   44,   44,   44,   34,   34,
       34,   34,   34,   44,   44,   44,   34,   34,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,  252,  262,
      252,   44,   44,   44,   34,   34,   44,   44,   44,   34,

       34,   44,   44,   44,   34,   44,   44,  252,  252,   44,
       44,   44,   34,   34,   34,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,  252,  252,  252,
      252,    0,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252
    } ;

static yyconst flex_int16_t yy_nxt[1177] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       10,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   28,   28,   28,   28,   28,   28,   29,   10,   30,
       31,   32,   33,   34,   35,   36,   37,   28,   28,   38,
       39,   40,   41,   28,   42,   43,   44,   45,   46,   28,
       28,   28,   28,   47,   60,   67,   60,   68,   69,  191,
       69,   71,  190,   48,   49,   73,   50,   68,   67,   69,
      105,   69,   69,  117,   69,   74,   51,   69,  118,   69,
       69,   60,   52,   60,   53,   69,   69,   74,   69,   69,
      111,   54,  124,   69,  124,  189,  112,   55,   47,   76,

      111,   69,   69,   69,   69,  158,  112,  159,   48,   49,
       69,   50,   69,   69,  161,  191,   69,   69,   69,   69,
       82,   51,  160,  190,  160,   77,   69,   52,   83,   53,
      189,   69,   69,   69,   69,   85,   54,  114,  158,  252,
      158,   70,   55,   69,  252,   69,   69,   69,   84,   70,
       73,  117,   68,   70,   87,   70,  118,  208,   88,   69,
       74,   86,  161,  209,   70,   78,  104,  120,   70,   79,
       70,   80,   74,   89,   81,   90,   70,   66,   64,   62,
       70,   91,   70,   70,   70,   70,  104,   70,   70,   70,
       70,   93,   70,   70,   70,  248,   75,   94,   70,   92,

       95,  249,   70,   70,   96,   72,   99,   70,   70,   70,
       70,  100,   70,   66,   70,   64,   97,   70,  250,  101,
       98,   70,   62,   70,  251,  102,   70,  103,   69,  252,
       69,   71,   73,   69,  105,   69,   69,   71,  106,   59,
       59,  108,   74,  107,   69,  121,   76,  109,   57,   69,
       70,  122,   70,   57,   74,   70,   70,  121,  110,  123,
       70,  113,   70,  125,   70,   88,   70,   70,   70,  126,
       70,  123,   70,   70,  252,  252,  127,  252,  252,   70,
       70,  252,   70,   70,   70,   70,   70,  128,   70,   70,
      252,   70,   70,   70,  129,   70,   70,   70,   70,   70,

      252,   70,   70,  252,   70,  132,  133,  252,   70,  252,
      252,  130,  131,   70,   70,   70,  252,   70,   70,   70,
       70,   70,  136,   70,   70,   70,   70,  134,  252,  252,
      252,  252,  252,  252,  252,   70,  135,   70,   70,   70,
      137,   70,   70,  252,   70,  252,   70,   70,  138,   70,
      252,  139,  252,   70,   70,  141,   70,  252,   70,   70,
       70,   70,  252,   70,   70,  140,   70,  252,  252,  142,
       70,  252,   70,   70,   70,   70,  252,   70,   70,   70,
       70,  143,   70,  252,   70,  252,   70,  144,   70,   70,
      145,   70,  146,   70,   70,   70,   70,   70,  252,  252,

       70,  148,  252,  252,   70,  252,  147,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,  252,  252,   70,
      252,  150,  252,  149,   70,  151,   70,  252,  252,   70,
       70,   70,   70,   73,   70,  105,   70,  152,   70,  154,
      153,   70,   70,   74,  107,  252,   70,  252,   70,  252,
       70,   70,  252,  252,   70,   74,   70,  252,   70,   70,
       70,   70,  146,  120,   70,   70,   70,   70,  122,   70,
       70,  157,  156,  155,   70,  252,  123,   70,   70,  252,
      164,   70,  165,  157,   70,  252,   70,   70,  123,  252,
      162,   70,  252,   70,  252,  163,   70,   70,   70,  252,

       70,   70,   70,   70,  167,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  166,   70,   70,   70,  252,   70,
       70,   70,   70,   70,   70,  168,   70,  169,  170,   70,
      252,   70,   70,   70,  172,  171,  252,  173,   70,   70,
       70,  175,   70,   70,  176,   70,   70,   70,   70,   70,
      174,   70,   70,   70,  252,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  252,   70,   70,   70,  177,  252,
       70,   70,   70,  178,   70,   70,   70,   70,   70,   70,
      185,  181,  179,   70,  183,  180,   70,   70,   70,  252,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  182,   70,   70,   70,  184,   70,   70,   70,   70,
      186,   70,   70,   70,  252,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  187,   70,  188,  252,   70,   70,
      193,  194,  192,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,  195,   70,
       70,  252,  196,  252,   70,  252,   70,   70,   70,   70,
       70,   70,   70,   70,  197,   70,   70,  252,   70,  252,
       70,  198,   70,   70,   70,   70,  252,   70,   70,   70,
      199,   70,   70,   70,   70,   70,   70,  252,   70,   70,

       70,  252,  201,   70,  252,  203,  202,  200,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  204,  205,   70,   70,   70,   70,   70,   70,   70,
      252,   70,   70,   70,  252,   70,   70,   70,   70,   70,
       70,  206,   70,   70,   70,   70,   70,   70,   70,  208,
       70,  252,   70,  252,  210,  209,   70,  207,  252,  252,
       70,   70,   70,  252,   70,   70,   70,  252,   70,   70,
      213,  252,   70,   70,   70,  252,   70,   70,   70,   70,
       70,   70,   70,   70,  211,   70,   70,   70,  252,   70,
       70,  252,   70,   70,  252,   70,   70,   70,   70,   70,

       70,   70,   70,  212,   70,  252,   70,  252,   70,   70,
       70,  214,  252,   70,  216,   70,   70,  252,   70,   70,
       70,   70,  217,  215,   70,   70,   70,  219,   70,   70,
       70,   70,  220,   70,   70,  218,   70,  252,   70,   70,
      252,   70,   70,   70,   70,   70,   70,   70,   70,   70,
      252,  223,  252,   70,  252,  221,  252,  224,  222,   70,
      252,  252,   70,   70,   70,   70,  252,   70,   70,  225,
      226,   70,   70,   70,  252,   70,   70,   70,   70,   70,
       70,   70,  227,   70,  228,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,  229,  252,  231,   70,   70,

      230,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  232,   70,   70,   70,   70,   70,   70,   70,  233,
      252,   70,   70,   70,  252,   70,  234,   70,   70,   70,
      252,   70,   70,   70,   70,   70,  252,   70,   70,   70,
      235,   70,   70,   70,   70,   70,  236,   70,   70,  252,
      252,   70,   70,  238,  252,  252,   70,  252,   70,  237,
       70,   70,   70,   70,   70,   70,  239,   70,   70,   70,
      252,   70,   70,   70,  252,   70,  240,   70,   70,   70,
       70,   70,   70,   70,  243,   70,  252,   70,  252,   70,
      241,   70,  242,   70,   70,   70,   70,  244,   70,   70,

       70,   70,   70,  252,   70,   70,  245,  252,   70,   70,
      248,   70,  252,   70,  252,   70,  249,   70,   70,  246,
       70,   70,   70,  252,   70,  247,   70,   70,  250,   70,
       70,   70,  252,   70,  251,  252,  252,  252,  252,  252,
       70,  252,   70,  252,   70,   70,   70,  252,  252,   70,
      252,  252,  252,  252,  252,  252,   70,  252,   70,  252,
       70,  252,   70,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,   70,  252,  252,  252,   70,   56,
       56,   56,   56,   56,   58,   58,   58,   58,   58,   61,
       61,   61,   61,   61,   63,   63,   63,   63,   63,   65,

       65,   65,   65,   65,   70,   70,  115,  115,  252,  115,
      115,  116,  116,  116,  116,  119,  252,  119,  119,  119,
       69,   69,    9,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252
    } ;

static yyconst flex_int16_t yy_chk[1177] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,   11,   20,   11,   20,   21,  191,
       21,   21,  190,    3,    3,   23,    3,   23,   48,   28,
       48,   28,   28,   57,   21,   23,    3,   32,   57,   32,
       32,   60,    3,   60,    3,   28,   33,   23,   33,   33,
       53,    3,   74,   32,   74,  189,   53,    3,    4,   32,

      111,   35,   33,   35,   35,  121,  111,  121,    4,    4,
       36,    4,   36,   36,  161,  160,   37,   35,   37,   37,
       35,    4,  123,  159,  123,   33,   36,    4,   35,    4,
      158,   38,   37,   38,   38,   37,    4,   55,  157,  116,
      157,   55,    4,   34,  116,   34,   34,   38,   36,   39,
       68,  117,   68,   39,   39,   39,  117,  208,   39,   34,
       68,   38,  124,  208,   40,   34,  104,   67,   40,   34,
       40,   34,   68,   40,   34,   41,   41,   65,   63,   61,
       41,   42,   41,   43,   42,   41,   47,   43,   42,   43,
       42,   43,   43,   42,   70,  248,   26,   43,   70,   42,

       44,  248,   45,   44,   44,   22,   45,   44,   45,   44,
       70,   45,   44,   15,   70,   14,   44,   46,  250,   45,
       44,   46,   13,   46,  250,   46,   46,   46,   49,    9,
       49,   49,   50,   51,   50,   51,   51,   71,   49,    8,
        7,   51,   50,   50,   49,   71,   52,   51,    6,   51,
       52,   73,   52,    5,   50,   52,   54,   71,   52,   73,
       54,   54,   54,   76,   77,   54,   78,   76,   77,   79,
       78,   73,   80,   79,    0,    0,   80,    0,    0,   76,
       77,    0,   78,   76,   77,   79,   78,   81,   80,   79,
        0,   81,   80,   81,   81,   82,   81,   84,   83,   82,

        0,   84,   83,    0,   85,   84,   85,    0,   85,    0,
        0,   82,   83,   84,   83,   82,    0,   84,   83,   86,
       85,   87,   88,   86,   85,   87,   88,   86,    0,    0,
        0,    0,    0,    0,    0,   86,   87,   87,   88,   86,
       89,   87,   88,    0,   89,    0,   89,   90,   89,   89,
        0,   90,    0,   90,   91,   92,   90,    0,   91,   92,
       91,   92,    0,   91,   92,   91,   93,    0,    0,   93,
       93,    0,   93,   94,   96,   93,    0,   94,   96,   94,
       95,   94,   94,    0,   95,    0,   95,   95,   97,   95,
       96,   98,   97,   99,   96,   98,  100,   99,    0,    0,

      100,   99,    0,    0,   97,    0,   98,   98,   97,   99,
      101,   98,  100,   99,  101,  102,  100,    0,    0,  102,
        0,  102,    0,  101,  102,  103,  101,    0,    0,  103,
      101,  103,  106,  105,  103,  105,  106,  106,  106,  110,
      109,  106,  108,  105,  105,    0,  108,    0,  108,    0,
      109,  108,    0,    0,  109,  105,  109,    0,  114,  109,
      110,  113,  114,  120,  110,  113,  110,  113,  122,  110,
      113,  120,  114,  113,  114,    0,  122,  125,  114,    0,
      127,  125,  128,  120,  127,    0,  128,  126,  122,    0,
      125,  126,    0,  125,    0,  126,  127,  125,  128,    0,

      127,  129,  128,  126,  130,  129,  131,  126,  130,  132,
      131,  133,  134,  132,  129,  133,  134,  129,    0,  135,
      130,  129,  131,  135,  130,  132,  131,  133,  134,  132,
        0,  133,  134,  137,  136,  135,    0,  137,  136,  135,
      136,  139,  138,  136,  140,  139,  138,  141,  140,  137,
      138,  141,  142,  137,    0,  143,  142,  139,  138,  143,
      140,  139,  138,  141,  140,  144,  145,  141,  142,  144,
      145,  143,  142,  146,    0,  143,  147,  146,  144,    0,
      147,  144,  145,  146,  148,  144,  145,  149,  148,  146,
      153,  149,  147,  146,  151,  148,  147,  153,  151,    0,

      148,  153,  150,  149,  148,  152,  150,  149,  150,  152,
      151,  150,  154,  153,  151,  152,  154,  153,  155,  156,
      154,  152,  155,  156,    0,  152,  162,  164,  154,  163,
      162,  164,  154,  163,  155,  156,  156,    0,  155,  156,
      163,  164,  162,  164,  165,  163,  162,  164,  165,  163,
      166,  167,  168,  169,  166,  167,  168,  169,  166,  169,
      165,    0,  169,    0,  165,    0,  166,  167,  168,  170,
      166,  167,  168,  170,  170,  170,  171,    0,  170,    0,
      171,  170,  171,  172,  173,  171,    0,  172,  173,  172,
      173,  174,  172,  173,  175,  174,  176,    0,  175,  177,

      176,    0,  175,  177,    0,  177,  176,  174,  177,  178,
      175,  174,  176,  178,  175,  178,  176,  179,  178,  180,
      181,  179,  182,  180,  181,  183,  182,  184,  185,  183,
        0,  184,  185,  179,    0,  180,  181,  179,  182,  180,
      181,  183,  182,  184,  185,  183,  186,  184,  185,  187,
      186,    0,  188,    0,  188,  187,  188,  186,    0,    0,
      192,  193,  186,    0,  192,  193,  186,    0,  188,  194,
      197,    0,  188,  194,  197,    0,  192,  193,  195,  187,
      192,  193,  195,  187,  195,  194,  197,  195,    0,  194,
      197,    0,  196,  198,    0,  187,  196,  198,  196,  187,

      199,  196,  200,  196,  199,    0,  200,    0,  200,  198,
      202,  200,    0,  198,  202,  201,  199,    0,  203,  201,
      199,  201,  203,  201,  201,  204,  202,  205,  206,  204,
      202,  205,  206,  205,  203,  204,  205,    0,  203,  207,
        0,  204,  210,  207,  206,  204,  210,  211,  206,  212,
        0,  211,    0,  212,    0,  207,    0,  212,  210,  207,
        0,    0,  210,  211,  213,  212,    0,  211,  213,  212,
      213,  214,  215,  213,    0,  214,  215,  214,  215,  216,
      214,  215,  214,  216,  215,  218,  217,  219,  220,  218,
      217,  219,  220,  221,  222,  216,    0,  221,  222,  216,

      217,  218,  217,  219,  220,  218,  217,  219,  220,  221,
      222,  222,  223,  221,  222,  224,  223,  225,  226,  224,
        0,  225,  226,  228,    0,  227,  226,  228,  223,  227,
        0,  224,  223,  225,  226,  224,    0,  225,  226,  228,
      227,  227,  229,  228,  230,  227,  229,  231,  230,    0,
        0,  231,  232,  231,    0,    0,  232,    0,  229,  230,
      230,  233,  229,  231,  230,  233,  232,  231,  232,  234,
        0,  235,  232,  234,    0,  235,  233,  233,  236,  237,
      238,  233,  236,  237,  238,  234,    0,  235,    0,  234,
      234,  235,  236,  239,  236,  237,  238,  239,  236,  237,

      238,  240,  241,    0,  242,  240,  241,    0,  242,  239,
      244,  243,    0,  239,    0,  243,  244,  240,  241,  242,
      242,  240,  241,    0,  242,  243,  245,  243,  247,  246,
      245,  243,    0,  246,  247,    0,    0,    0,    0,    0,
      244,    0,  245,    0,  244,  246,  245,    0,    0,  246,
        0,    0,    0,    0,    0,    0,  244,    0,  247,    0,
      244,    0,  247,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  247,    0,    0,    0,  247,  253,
      253,  253,  253,  253,  254,  254,  254,  254,  254,  255,
      255,  255,  255,  255,  256,  256,  256,  256,  256,  257,

      257,  257,  257,  257,  258,  258,  259,  259,    0,  259,
      259,  260,  260,  260,  260,  261,    0,  261,  261,  261,
      262,  262,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int zz_flex_debug;
int zz_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *zztext;
#line 1 "scanner.ll"
/* -*-C++-*- */
#line 3 "scanner.ll"
#include <iostream>
#include <string>
#include <cstring>
#include <compiler/ParseTree.h>
#include "parser.h"

    std::vector<FILE*> file_stack;
    int command_buffer_count = 0;
    int buffer_count = 0;
    void return_to_main_buffer();
    void close_buffer();
    std::string ExpandFileName(char const *name);



#line 829 "scanner.cc"

#define INITIAL 0
#define RDATA 1
#define COMMENT 2
#define SYSTEM 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int zzlex_destroy (void );

int zzget_debug (void );

void zzset_debug (int debug_flag  );

YY_EXTRA_TYPE zzget_extra (void );

void zzset_extra (YY_EXTRA_TYPE user_defined  );

FILE *zzget_in (void );

void zzset_in  (FILE * in_str  );

FILE *zzget_out (void );

void zzset_out  (FILE * out_str  );

int zzget_leng (void );

char *zzget_text (void );

int zzget_lineno (void );

void zzset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int zzwrap (void );
#else
extern int zzwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( zztext, zzleng, 1, zzout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( zzin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( zzin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, zzin))==0 && ferror(zzin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(zzin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int zzlex (void);

#define YY_DECL int zzlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after zztext and zzleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 26 "scanner.ll"


#line 1017 "scanner.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! zzin )
			zzin = stdin;

		if ( ! zzout )
			zzout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			zzensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				zz_create_buffer(zzin,YY_BUF_SIZE );
		}

		zz_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of zztext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1123 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "scanner.ll"
zzlval.intval=MODEL; return MODEL;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "scanner.ll"
zzlval.intval=DATA; return DATA;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "scanner.ll"
zzlval.intval=IN; return IN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "scanner.ll"
zzlval.intval=TO; return TO;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "scanner.ll"
zzlval.intval=INITS; return INITS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "scanner.ll"
zzlval.intval=PARAMETERS; return PARAMETERS;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "scanner.ll"
zzlval.intval=COMPILE; return COMPILE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "scanner.ll"
zzlval.intval=NCHAINS; return NCHAINS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "scanner.ll"
zzlval.intval=INITIALIZE; return INITIALIZE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "scanner.ll"
zzlval.intval=CHAIN; return CHAIN;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "scanner.ll"
zzlval.intval=UPDATE; return UPDATE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "scanner.ll"
zzlval.intval=ADAPT; return ADAPT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "scanner.ll"
zzlval.intval=BY; return BY;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "scanner.ll"
zzlval.intval=MONITOR; return MONITOR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "scanner.ll"
zzlval.intval=MONITORS; return MONITORS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "scanner.ll"
zzlval.intval=TYPE; return TYPE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "scanner.ll"
zzlval.intval=SET; return SET;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "scanner.ll"
zzlval.intval=CLEAR; return CLEAR;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "scanner.ll"
zzlval.intval=THIN; return THIN;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "scanner.ll"
zzlval.intval=SAMPLER; return SAMPLER;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "scanner.ll"
zzlval.intval=SAMPLERS; return SAMPLERS;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 52 "scanner.ll"
zzlval.intval=RNGTOK; return RNGTOK;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 53 "scanner.ll"
zzlval.intval=FACTORY; return FACTORY;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 54 "scanner.ll"
zzlval.intval=FACTORIES; return FACTORIES;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "scanner.ll"
zzlval.intval=CODA; return CODA;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "scanner.ll"
zzlval.intval=STEM; return STEM;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "scanner.ll"
zzlval.intval=LOAD; return LOAD;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "scanner.ll"
zzlval.intval=UNLOAD; return UNLOAD;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "scanner.ll"
zzlval.intval=EXIT; return EXIT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "scanner.ll"
zzlval.intval=DIRECTORY; return DIRECTORY;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "scanner.ll"
zzlval.intval=CD; return CD;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "scanner.ll"
zzlval.intval=PWD; return PWD;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "scanner.ll"
zzlval.intval=RUN; return RUN;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "scanner.ll"
zzlval.intval=LIST; return LIST;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "scanner.ll"
return ',';
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "scanner.ll"
return '[';
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "scanner.ll"
return ']';
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "scanner.ll"
return '(';
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "scanner.ll"
return ')';
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "scanner.ll"
return '=';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "scanner.ll"
return ARROW;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "scanner.ll"
return '*';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "scanner.ll"
return ':';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "scanner.ll"
return ';';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "scanner.ll"
return '`';
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "scanner.ll"
BEGIN(COMMENT);
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 83 "scanner.ll"
/* Eat up anything that's not a '*'   */
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 84 "scanner.ll"
/* Eat up '*'s not followed by a '/'  */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "scanner.ll"
BEGIN(INITIAL);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "scanner.ll"
/* Eat whitespace */
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 88 "scanner.ll"
/* Eat comments */
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 89 "scanner.ll"
/* Eat newlines */
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 90 "scanner.ll"
return ENDCMD;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "scanner.ll"
BEGIN(SYSTEM);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "scanner.ll"
{
  zzlval.stringptr = new std::string(zztext);
  return SYSCMD;
}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 97 "scanner.ll"
{
    BEGIN(INITIAL); return ENDCMD;
 }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 101 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 104 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "scanner.ll"
{
  zzlval.intval = atoi(zztext); return INT;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 126 "scanner.ll"
return DIM;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "scanner.ll"
return NA;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 128 "scanner.ll"
return R_NULL;
	YY_BREAK
case 68:
*yy_cp = (yy_hold_char); /* undo effects of setting up zztext */
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up zztext again */
YY_RULE_SETUP
#line 129 "scanner.ll"
return STRUCTURE;
	YY_BREAK
case 69:
*yy_cp = (yy_hold_char); /* undo effects of setting up zztext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up zztext again */
YY_RULE_SETUP
#line 130 "scanner.ll"
return LIST;
	YY_BREAK
case 70:
*yy_cp = (yy_hold_char); /* undo effects of setting up zztext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up zztext again */
YY_RULE_SETUP
#line 131 "scanner.ll"
return 'c';
	YY_BREAK
case 71:
*yy_cp = (yy_hold_char); /* undo effects of setting up zztext */
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up zztext again */
YY_RULE_SETUP
#line 132 "scanner.ll"
return ASINTEGER;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 134 "scanner.ll"
{ 
  zzlval.stringptr = new std::string(zztext);
  return NAME;
}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 139 "scanner.ll"
{
  zzlval.stringptr = new std::string(zztext);
  // Remove enclosing quotes
  zzlval.stringptr->erase(zzlval.stringptr->size() - 1, 1);
  zzlval.stringptr->erase(0, 1);
  return STRING;
}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 147 "scanner.ll"
{
    zzlval.stringptr = new std::string(zztext);
    zzlval.stringptr->erase(zzlval.stringptr->size() - 1, 1);
    zzlval.stringptr->erase(0,1);
    return STRING;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 154 "scanner.ll"
{
    if (command_buffer_count) {
	close_buffer();
	--command_buffer_count;
    }
    else {
	yyterminate();
    }
    return ENDSCRIPT;
}
	YY_BREAK
case YY_STATE_EOF(RDATA):
#line 164 "scanner.ll"
{
    close_buffer();
    BEGIN(INITIAL);
    return ENDDATA;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 169 "scanner.ll"
ECHO;
	YY_BREAK
#line 1551 "scanner.cc"
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SYSTEM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed zzin at a new source and called
			 * zzlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = zzin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( zzwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * zztext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of zzlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					zzrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			zzrestart(zzin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) zzrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 252);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up zztext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					zzrestart(zzin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( zzwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve zztext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void zzrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        zzensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            zz_create_buffer(zzin,YY_BUF_SIZE );
	}

	zz_init_buffer(YY_CURRENT_BUFFER,input_file );
	zz_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void zz_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		zzpop_buffer_state();
	 *		zzpush_buffer_state(new_buffer);
     */
	zzensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	zz_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (zzwrap()) processing, but the only time this flag
	 * is looked at is after zzwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void zz_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	zzin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE zz_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) zzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in zz_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) zzalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in zz_create_buffer()" );

	b->yy_is_our_buffer = 1;

	zz_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with zz_create_buffer()
 * 
 */
    void zz_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		zzfree((void *) b->yy_ch_buf  );

	zzfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a zzrestart() or at EOF.
 */
    static void zz_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	zz_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then zz_init_buffer was _probably_
     * called from zzrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void zz_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		zz_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void zzpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	zzensure_buffer_stack();

	/* This block is copied from zz_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from zz_switch_to_buffer. */
	zz_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void zzpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	zz_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		zz_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void zzensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)zzalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in zzensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)zzrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in zzensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE zz_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) zzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in zz_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	zz_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to zzlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       zz_scan_bytes() instead.
 */
YY_BUFFER_STATE zz_scan_string (yyconst char * yystr )
{
    
	return zz_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to zzlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE zz_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) zzalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in zz_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = zz_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in zz_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up zztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		zztext[zzleng] = (yy_hold_char); \
		(yy_c_buf_p) = zztext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		zzleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int zzget_lineno  (void)
{
        
    return zzlineno;
}

/** Get the input stream.
 * 
 */
FILE *zzget_in  (void)
{
        return zzin;
}

/** Get the output stream.
 * 
 */
FILE *zzget_out  (void)
{
        return zzout;
}

/** Get the length of the current token.
 * 
 */
int zzget_leng  (void)
{
        return zzleng;
}

/** Get the current token.
 * 
 */

char *zzget_text  (void)
{
        return zztext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void zzset_lineno (int  line_number )
{
    
    zzlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see zz_switch_to_buffer
 */
void zzset_in (FILE *  in_str )
{
        zzin = in_str ;
}

void zzset_out (FILE *  out_str )
{
        zzout = out_str ;
}

int zzget_debug  (void)
{
        return zz_flex_debug;
}

void zzset_debug (int  bdebug )
{
        zz_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from zzlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    zzin = stdin;
    zzout = stdout;
#else
    zzin = (FILE *) 0;
    zzout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * zzlex_init()
     */
    return 0;
}

/* zzlex_destroy is for both reentrant and non-reentrant scanners. */
int zzlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		zz_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		zzpop_buffer_state();
	}

	/* Destroy the stack itself. */
	zzfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * zzlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *zzalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *zzrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void zzfree (void * ptr )
{
	free( (char *) ptr );	/* see zzrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 169 "scanner.ll"



int zzwrap()
{
  return 1;
}

void push_file(FILE *file) {
    file_stack.push_back(file);
}

void pop_file() {
    if (file_stack.empty())
        return;

    fclose(file_stack.back());
    file_stack.pop_back();
}


bool open_data_buffer(std::string const *name) {
    FILE *file = fopen(ExpandFileName(name->c_str()).c_str(),"r");
    if (file) {
	zzpush_buffer_state(zz_create_buffer(file, YY_BUF_SIZE));
	push_file(file);
        ++buffer_count;
	BEGIN(RDATA);
	return true;
    }
    else {
	return false;
    }
}

void close_buffer() {
    zzpop_buffer_state();
    pop_file();
    --buffer_count;
}
    
bool open_command_buffer(std::string const *name) {
    FILE *file = fopen(name->c_str(),"r");
    if (file) {
	file_stack.push_back(file);
	zzpush_buffer_state(zz_create_buffer(file, YY_BUF_SIZE ));
	++command_buffer_count;
        ++buffer_count;
	return true;
    }
    else {
	return false;
    }
}

void return_to_main_buffer() {
    /* Clear all buffers in the stack and return to the first */
    while(buffer_count) {
	zzpop_buffer_state();
	--buffer_count;
    }
    command_buffer_count = 0;
    BEGIN(INITIAL);
}


